### ISSUE TITLE
Training time is so long and hard to achieve the SOTA results. 

### ISSUE THREAD

**Issue by wenyang001** [passerer/HPINet#5]
I have tried to train the HPINet-M model at a scale of x4 using 4 rtx 3090 gpus. Based on your original configuration without any modification, it takes 3 days to finish 260 epoch training (the required training epoch is 420). But the PSNR of Set5 and Set14 seems to converage at 32.39 and 28.77, respectively. 

I just want to know whether the training time is normal and whether small tricks are needed to achieve the results in the paper.

<img width="1179" alt="image" src="https://github.com/passerer/HPINet/assets/109712056/cd008d74-66ce-4315-85bc-7b3758e32e3b">

**Comment by passerer** [comment]
Thank you for your interest. Due to the inclusion of attention modules in HPINet, the training process requires much computational resources and GPU memory. As mentioned in the paper and README, we had to use 8 V100 GPUs with 32GB of memory each to meet the training requirements. I'm unsure if using 4 RTX 3090 GPUs would be sufficient to achieve the desired batch size and patch size as specified in [train.py](https://github.com/passerer/HPINet/blob/25d5db1422df50b1671aae6f6ec3a2953fa352c5/train.py#L60). Could you please provide the reproduction results on BSD100, Urban100, and Manga109?

**Comment by wenyang001** [comment]
The configuration remains the same in the train.py with the min_batch_size=8 and max_batch_size=64; min_patch_size = 192 and max_patch_size = 720. 

The reproduction results are attached. Thanks.

<img width="420" alt="image" src="https://github.com/passerer/HPINet/assets/109712056/4c181fa3-191b-4ec6-b35a-141915c29360">

**Comment by wenyang001** [comment]
The reproduction results at the 420 epoch are attached. 

<img width="446" alt="image" src="https://github.com/passerer/HPINet/assets/109712056/d5437d00-66da-4890-a4ed-09813fbeb8bb">

**Comment by passerer** [comment]
I have tried training with four 24G GPUs  like you did, but I encounter the memory exceed issue. For better results, the training utilizes a patch size that increases with each epoch, leading to a gradual increase in GPU memory usage until it exceeds the capacity of 24G. Therefore, I have no idea that why four 24G GPUs worked perfectly for you. If you're interested, we recommend starting with HPINet-S, as it requires less training time and consumes less memory.

We are planning to release a new training framework in the coming weeks that addresses the issue of excessive GPU memory usage. We will create a new branch and notify you once it's available.

**Comment by passerer** [comment]
Here is another [code](https://github.com/EquationWalker/HPINet). It can be accommodated by four GPUs.

**Comment by passerer** [comment]
If there are further questions, feel free to reopen this issue at any time.

**Comment by wenyang001** [comment]
Thank you for your reply. It helps me a lot.
